# Generated by Django 4.2.7 on 2023-12-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPublicacion', models.IntegerField()),
                ('nombreUsuario', models.CharField(max_length=15)),
                ('comentario', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
